"""
Data-driven Dragon Ball technique catalog.

This module defines the full technique registry used by commands, UI, quest rewards
and future combat resolution. Entries are intentionally complete but mostly stubbed
at the execution layer so they can integrate without combat rewrites.
"""

from __future__ import annotations

from world.content_core import build_registry, find_by_key_or_name, make_stub_result, summarize_effect


def _damage(base, kind="ki", **scaling):
    data = {
        "type": "damage",
        "damage_kind": kind,
        "base_damage": base,
        "scaling": {
            "base": base,
            "strength": scaling.get("strength", 0.2),
            "speed": scaling.get("speed", 0.1),
            "mastery": scaling.get("mastery", 0.2),
            "ki_control": scaling.get("ki_control", 0.2),
            "pl": scaling.get("pl", 0.0018),
            "power_level_hook": scaling.get("power_level_hook", "standard"),
        },
    }
    if scaling.get("notes"):
        data["scaling"]["notes"] = scaling["notes"]
    return data


def _tech(
    key,
    name,
    category,
    desc,
    tags,
    ki_cost,
    cooldown,
    *,
    damage_base=0,
    damage_factor=1.0,
    accuracy=80,
    effect=None,
    cast_time=0.0,
    range_band="mid",
    target="enemy",
    prerequisites=None,
    extras=None,
    vfx_id=None,
    aliases=None,
):
    effect = effect or {"type": "utility", "summary": "No effect data"}
    scaling = effect.get("scaling", {}) if isinstance(effect, dict) else {}
    # Add damage stats to effect for damage-dealing techniques
    if damage_base > 0:
        if isinstance(effect, dict):
            effect["base_damage"] = damage_base
            effect["damage_factor"] = damage_factor
            effect["accuracy"] = accuracy
    return (
        key,
        {
            "name": name,
            "display_name": name,
            "description": desc,
            "category": category,
            "tags": list(tags),
            "resource_costs": {"ki": int(ki_cost)},
            "ki_cost": int(ki_cost),  # backwards-compatible convenience field
            "cooldown": float(cooldown),
            "cast_time": float(cast_time),
            "base_effect_magnitude": effect.get("base_damage") if effect.get("type") == "damage" else effect,
            "effect": effect,
            "scaling": scaling,
            "target_rules": {"target": target, "range": range_band},
            "prerequisites": prerequisites or {},
            "context_extras": extras or {},
            "vfx_id": vfx_id or f"vfx_{key}",
            "aliases": aliases or [],
            "ui_summary": summarize_effect({"effect": effect, "scaling": scaling, "tags": tags}),
            "framework": "Technique",
            "ready_state": "stub_integration_ready",
        },
    )


_T = [
    # Fundamentals / blasts
    _tech(
        "ki_blast",
        "Ki Blast",
        "ki",
        "A fast, compact ki shot used in every serious exchange from sparring to war.",
        ["ki", "ranged", "damage", "starter"],
        10,
        2.5,
        effect=_damage(14, "ki", strength=0.25, mastery=0.2, ki_control=0.35, pl=0.0017),
        extras={"chain_window": 1.2, "combo_builder": True},
        aliases=["blast"],
    ),
    _tech(
        "consecutive_energy_blast",
        "Consecutive Energy Blast",
        "ki",
        "A rapid-fire volley of palm blasts that floods the target's guard with pressure.",
        ["ki", "ranged", "damage", "combo"],
        18,
        5.0,
        effect=_damage(20, "ki", speed=0.25, mastery=0.25, ki_control=0.25, pl=0.0016),
        extras={"multi_hit": 4, "guard_chip": 0.18},
    ),
    _tech(
        "scatter_shot",
        "Scatter Shot",
        "ki",
        "A cluster of seeking ki pellets that spread then collapse on the target.",
        ["ki", "ranged", "damage", "control"],
        20,
        6.0,
        effect=_damage(22, "ki", speed=0.18, mastery=0.28, ki_control=0.28, pl=0.0017),
        extras={"tracking": "medium", "anti_dash_bias": 0.12},
    ),
    _tech(
        "spirit_shot",
        "Spirit Shot",
        "ki",
        "A guided ki sphere that can be steered after launch by disciplined control.",
        ["ki", "ranged", "damage", "utility"],
        24,
        7.0,
        effect=_damage(26, "ki", mastery=0.22, ki_control=0.42, pl=0.0018),
        extras={"guidance": True, "beam_struggle_participation": False},
    ),
    _tech(
        "death_beam",
        "Death Beam",
        "ki",
        "Frieza-force precision condensed into a finger-fired piercing ray.",
        ["ki", "ranged", "damage", "piercing"],
        16,
        4.5,
        effect=_damage(24, "pierce", speed=0.2, mastery=0.25, ki_control=0.38, pl=0.0018),
        extras={"armor_pierce": 0.2, "interrupt_bias": 0.08},
    ),
    _tech(
        "dodon_ray",
        "Dodon Ray",
        "ki",
        "A Crane School finger beam optimized for quick execution and surprising lethality.",
        ["ki", "ranged", "damage"],
        15,
        4.0,
        effect=_damage(22, "pierce", speed=0.15, mastery=0.25, ki_control=0.32, pl=0.0018),
        cast_time=0.1,
        extras={"quick_cast": True},
    ),
    _tech(
        "finger_beam_burst",
        "Finger Beam Burst",
        "ki",
        "A fan of finger beams meant to punish evasive movement and mid-range footwork.",
        ["ki", "ranged", "damage", "control"],
        21,
        5.5,
        effect=_damage(23, "ki", speed=0.22, mastery=0.2, ki_control=0.32, pl=0.0016),
        extras={"multi_projectile": 3, "zone_pressure": True},
    ),
    _tech(
        "destructo_disc",
        "Destructo Disc",
        "ki",
        "A razor-thin spinning disc that trades charge time for brutal cutting power.",
        ["ki", "ranged", "damage", "piercing", "control"],
        28,
        8.5,
        effect=_damage(34, "slice", mastery=0.3, ki_control=0.4, strength=0.05, pl=0.0019),
        cast_time=0.4,
        extras={"guard_break": 0.24, "limb_risk_hook": True},
    ),
    _tech(
        "kienzan_barrage",
        "Kienzan Barrage",
        "ki",
        "Multiple cutting discs launched in staggered timing to trap evasive targets.",
        ["ki", "ranged", "damage", "control", "multi_hit"],
        36,
        11.0,
        effect=_damage(38, "slice", mastery=0.28, ki_control=0.38, speed=0.16, pl=0.0020),
        cast_time=0.6,
        extras={"multi_hit": 3, "tracking": "low", "guard_break": 0.18},
    ),
    _tech(
        "eraser_cannon",
        "Eraser Cannon",
        "ki",
        "A Broly-style heavy orb fired with crushing force and unstable pressure.",
        ["ki", "ranged", "damage", "knockback"],
        34,
        9.0,
        effect=_damage(40, "ki", strength=0.2, mastery=0.18, ki_control=0.26, pl=0.0023),
        extras={"knockback": "heavy", "blast_radius": 1},
    ),
    _tech(
        "buster_cannon",
        "Buster Cannon",
        "ki",
        "A dense chest-level projectile favored in high-pressure exchanges by future warriors.",
        ["ki", "ranged", "damage"],
        30,
        8.0,
        effect=_damage(33, "ki", strength=0.12, mastery=0.24, ki_control=0.3, pl=0.0021),
        extras={"charge_synergy": 0.15},
    ),
    _tech(
        "masenko",
        "Masenko",
        "beam",
        "A sharp forward beam with fast release and strong mid-range pressure.",
        ["ki", "beam", "damage"],
        24,
        6.0,
        effect=_damage(28, "beam", mastery=0.22, ki_control=0.34, pl=0.0022),
        extras={"beam_struggle_participation": True},
        vfx_id="vfx_masenko",
    ),
    # Beams / heavy finishers
    _tech(
        "kame_wave",
        "Kamehameha",
        "beam",
        "The Turtle School's iconic wave: stable, scalable, and devastating in trained hands.",
        ["ki", "beam", "damage", "starter"],
        24,
        6.0,
        cast_time=0.5,
        effect=_damage(24, "beam", strength=0.18, mastery=0.35, ki_control=0.32, pl=0.0024),
        extras={"beam_struggle_participation": True, "charge_synergy": 0.2},
        aliases=["kamehameha", "kame"],
        vfx_id="vfx_kame_wave",
    ),
    _tech(
        "super_kamehameha",
        "Super Kamehameha",
        "beam",
        "A fully committed Kamehameha burst with superior compression and output.",
        ["ki", "beam", "damage"],
        42,
        12.0,
        cast_time=1.0,
        effect=_damage(48, "beam", mastery=0.38, ki_control=0.34, pl=0.0028),
        extras={"beam_struggle_participation": True, "guard_break": 0.2},
    ),
    _tech(
        "galick_gun",
        "Galick Gun",
        "beam",
        "A Saiyan-pride beam tuned for high output and beam struggle dominance.",
        ["ki", "beam", "damage"],
        28,
        7.5,
        cast_time=0.45,
        effect=_damage(30, "beam", strength=0.14, mastery=0.3, ki_control=0.34, pl=0.0025),
        extras={"beam_struggle_participation": True, "beam_struggle_bias": 0.08},
    ),
    _tech(
        "final_flash",
        "Final Flash",
        "beam",
        "A long charge, catastrophic beam that threatens even superior foes if it lands clean.",
        ["ki", "beam", "damage", "charge"],
        55,
        16.0,
        cast_time=1.4,
        effect=_damage(64, "beam", strength=0.12, mastery=0.4, ki_control=0.36, pl=0.0031),
        extras={"beam_struggle_participation": True, "charge_synergy": 0.35, "telegraph": "high"},
    ),
    _tech(
        "big_bang_attack",
        "Big Bang Attack",
        "ki",
        "A compact annihilation sphere detonated with exacting Saiyan control.",
        ["ki", "ranged", "damage", "blast"],
        34,
        9.0,
        effect=_damage(40, "explosive", mastery=0.26, ki_control=0.34, pl=0.0025),
        extras={"blast_radius": 2, "guard_chip": 0.16},
    ),
    _tech(
        "burning_attack",
        "Burning Attack",
        "beam",
        "A rapid sequence hand-sign release that converts timing into beam pressure.",
        ["ki", "beam", "damage", "utility"],
        30,
        8.0,
        cast_time=0.35,
        effect=_damage(34, "beam", speed=0.18, mastery=0.28, ki_control=0.34, pl=0.0024),
        extras={"beam_struggle_participation": True, "fast_release": True},
    ),
    _tech(
        "finish_buster",
        "Finish Buster",
        "beam",
        "A balanced future-era finisher built to punish openings with controlled output.",
        ["ki", "beam", "damage"],
        32,
        8.5,
        cast_time=0.5,
        effect=_damage(36, "beam", mastery=0.28, ki_control=0.32, pl=0.0025),
        extras={"beam_struggle_participation": True, "anti_guard_bias": 0.1},
    ),
    _tech(
        "special_beam_cannon",
        "Special Beam Cannon",
        "beam",
        "Piccolo's spiraling drill beam, built to pierce armor and stubborn guards.",
        ["ki", "beam", "damage", "piercing", "charge"],
        38,
        12.0,
        cast_time=1.1,
        effect=_damage(46, "pierce_beam", mastery=0.34, ki_control=0.38, pl=0.0027),
        extras={"beam_struggle_participation": True, "armor_pierce": 0.28, "guard_break": 0.22},
        aliases=["makankosappo"],
    ),
    _tech(
        "makosen",
        "Makosen",
        "beam",
        "A fierce Demon Clan beam with explosive release and broad impact pressure.",
        ["ki", "beam", "damage", "blast"],
        33,
        9.0,
        cast_time=0.55,
        effect=_damage(37, "beam", mastery=0.3, ki_control=0.3, pl=0.0025),
        extras={"beam_struggle_participation": True, "blast_radius": 1},
    ),
    _tech(
        "crusher_ball",
        "Crusher Ball",
        "ki",
        "A spinning compressed sphere that detonates with brutal localized force.",
        ["ki", "ranged", "damage", "blast"],
        31,
        8.5,
        effect=_damage(35, "explosive", mastery=0.24, ki_control=0.28, pl=0.0024),
        extras={"knockback": "medium"},
    ),
    _tech(
        "death_ball",
        "Death Ball",
        "ki",
        "A tyrant-class annihilation sphere meant to overwhelm space and morale alike.",
        ["ki", "ranged", "damage", "blast", "charge"],
        60,
        18.0,
        cast_time=1.5,
        effect=_damage(70, "explosive", mastery=0.28, ki_control=0.34, pl=0.0032),
        extras={"blast_radius": 3, "guard_break": 0.24, "telegraph": "high"},
    ),
    _tech(
        "supernova",
        "Supernova",
        "ki",
        "An emperor-level sphere of destruction that rewards setup and battlefield control.",
        ["ki", "ranged", "damage", "blast", "charge"],
        66,
        20.0,
        cast_time=1.7,
        effect=_damage(76, "explosive", mastery=0.3, ki_control=0.34, pl=0.0034),
        extras={"blast_radius": 4, "charge_synergy": 0.25},
    ),
    _tech(
        "omega_blaster",
        "Omega Blaster",
        "beam",
        "A monstrous Broly beam burst that favors raw pressure and knockback over finesse.",
        ["ki", "beam", "damage", "knockback"],
        52,
        14.0,
        cast_time=0.9,
        effect=_damage(58, "beam", strength=0.2, mastery=0.2, ki_control=0.2, pl=0.0030),
        extras={"beam_struggle_participation": True, "knockback": "heavy"},
    ),
    _tech(
        "big_bang_kamehameha",
        "Big Bang Kamehameha",
        "beam",
        "Fusion-level hybrid beam that fuses precision compression with explosive output.",
        ["ki", "beam", "damage", "advanced"],
        62,
        18.0,
        cast_time=1.2,
        effect=_damage(72, "beam", mastery=0.36, ki_control=0.4, pl=0.0033),
        extras={"beam_struggle_participation": True, "guard_break": 0.2, "charge_synergy": 0.22},
    ),
    _tech(
        "vanishing_ball",
        "Vanishing Ball",
        "ki",
        "A deceptive Majin sphere with odd timing and difficult visual reads.",
        ["ki", "ranged", "damage", "control"],
        29,
        8.0,
        effect=_damage(34, "explosive", mastery=0.24, ki_control=0.28, pl=0.0024),
        extras={"delayed_detonation": True, "flash_bias": 0.06},
    ),
    # Utility / control / defense
    _tech(
        "evil_containment_wave",
        "Evil Containment Wave",
        "utility",
        "A sealing technique that can restrain foes if setup and control checks succeed.",
        ["ki", "utility", "control"],
        40,
        18.0,
        cast_time=1.3,
        effect={"type": "seal", "base_chance": 0.18, "duration": 6.0, "summary": "Seal attempt with setup bonus"},
        prerequisites={"quest": "kami_sealing_trials", "trainer": "master_roshi"},
        extras={"requires_container_hook": True, "target_weakened_bonus": 0.2},
    ),
    _tech(
        "solar_flare",
        "Solar Flare",
        "control",
        "A blinding burst of light that disrupts vision and creates a tempo reset.",
        ["ki", "utility", "control", "flash", "stun"],
        16,
        9.0,
        effect={"type": "stun", "duration": 2.0, "secondary": "blind", "summary": "Flash-stun + interrupt"},
        extras={"interrupts_charging": True, "cone": True},
        vfx_id="vfx_solar_flare",
    ),
    _tech(
        "guard",
        "Guard",
        "defense",
        "A disciplined ki guard stance that shaves damage while you weather a burst.",
        ["ki", "utility", "defense", "self", "starter"],
        8,
        5.0,
        effect={"type": "guard", "duration": 3.0, "reduction": 0.45, "summary": "Damage reduction stance"},
        target="self",
        range_band="self",
        vfx_id="vfx_guard_sphere",
    ),
    _tech(
        "barrier",
        "Barrier",
        "defense",
        "A spherical ki barrier that trades ki efficiency for reliable burst protection.",
        ["ki", "utility", "defense", "self"],
        22,
        10.0,
        effect={"type": "guard", "duration": 2.5, "reduction": 0.62, "summary": "Short heavy damage reduction"},
        target="self",
        range_band="self",
        extras={"barrier_hook": True, "beam_block_bias": 0.16},
    ),
    _tech(
        "afterimage_dash",
        "Afterimage Dash",
        "movement",
        "A burst-step that leaves afterimages and ruins target tracking for a moment.",
        ["ki", "utility", "movement", "evasion", "starter"],
        14,
        7.5,
        effect={"type": "movement", "duration": 2.0, "summary": "Evasion buff / afterimage"},
        target="self",
        range_band="self",
        vfx_id="vfx_afterimage",
    ),
    _tech(
        "wild_sense",
        "Wild Sense",
        "utility",
        "Battle instinct spikes to read angles and punish predictable follow-ups.",
        ["ki", "utility", "self", "counter"],
        18,
        11.0,
        effect={"type": "counter_stance", "duration": 4.0, "summary": "Counter-read stance"},
        target="self",
        range_band="self",
        extras={"counter_hook": True, "anti_vanish_bias": 0.14},
    ),
    _tech(
        "instant_transmission",
        "Instant Transmission",
        "utility",
        "A lock-on teleport requiring ki sense; ideal for repositioning or pursuit.",
        ["ki", "utility", "movement", "teleport"],
        26,
        12.0,
        effect={"type": "movement", "summary": "Teleport to sensed target/location anchor"},
        target="self",
        range_band="long",
        prerequisites={"trainer": "goku", "ki_control_min": 25},
        extras={"teleport_hook": True, "requires_sense_lock": True},
    ),
    _tech(
        "explosive_wave",
        "Explosive Wave",
        "utility",
        "A radial ki burst used to break pressure, stagger nearby foes, and reset space.",
        ["ki", "utility", "control", "area", "knockback"],
        24,
        9.5,
        effect={"type": "aoe_pulse", "base_damage": 16, "radius": 2, "summary": "Area knockback pulse"},
        target="area",
        range_band="self",
        extras={"knockback": "medium", "interrupt_bias": 0.12},
    ),
    _tech(
        "gravity_bind",
        "Gravity Bind",
        "control",
        "Compresses local gravity around a target, slowing movement and escape windows.",
        ["ki", "utility", "control", "debuff"],
        22,
        10.5,
        effect={"type": "snare", "duration": 3.0, "slow": 0.35, "summary": "Movement slow / bind"},
        extras={"anti_dash_bias": 0.25},
    ),
    _tech(
        "telekinesis_hold",
        "Telekinesis Hold",
        "control",
        "A focused psychic grip that arrests motion briefly if concentration is maintained.",
        ["ki", "utility", "control", "stun"],
        28,
        12.0,
        cast_time=0.25,
        effect={"type": "hold", "duration": 2.5, "summary": "Short immobilize / concentration"},
        prerequisites={"race_any": ["grey", "kai"], "or_trainer": "supreme_kai"},
        extras={"channel_hook": True, "break_on_hit": True},
    ),
    _tech(
        "ki_suppression",
        "Ki Suppression",
        "utility",
        "Compress your signature and dampen battle aura to mislead scanners and senses.",
        ["ki", "utility", "self", "resource"],
        10,
        3.0,
        effect={"type": "resource", "summary": "Toggle suppression / signature masking"},
        target="self",
        range_band="self",
        extras={"suppression_factor_hook": True},
    ),
    _tech(
        "power_up_charge",
        "Power Up Charge",
        "utility",
        "A concentrated power-up sequence that converts time and risk into combat tempo.",
        ["ki", "utility", "self", "charge", "starter"],
        0,
        2.0,
        effect={"type": "resource", "summary": "Charge stance / combo with charge stacks"},
        target="self",
        range_band="self",
        extras={"uses_charge_system": True, "charge_synergy": True},
    ),
    _tech(
        "feint_step",
        "Feint Step",
        "movement",
        "A short vanish-step feint that baits guards and creates melee opening frames.",
        ["ki", "utility", "movement", "melee"],
        12,
        6.0,
        effect={"type": "movement", "summary": "Short reposition + guard bait"},
        target="self",
        range_band="self",
        extras={"guard_break_setup": 0.12},
    ),
    # Melee / rush techniques
    _tech(
        "vanish_strike",
        "Vanish Strike",
        "melee",
        "Instant acceleration into a hard strike that can interrupt ki charging.",
        ["melee", "damage", "interrupt", "starter"],
        18,
        8.5,
        effect=_damage(18, "impact", strength=0.45, speed=0.28, mastery=0.22, ki_control=0.08, pl=0.0018),
        extras={"interrupts_charging": True, "gap_close": True},
        vfx_id="vfx_vanish_strike",
    ),
    _tech(
        "wolf_fang_fist",
        "Wolf Fang Fist",
        "melee",
        "A relentless clawing rush that converts speed and pressure into combo damage.",
        ["melee", "damage", "combo", "rush"],
        16,
        7.0,
        effect=_damage(24, "impact", strength=0.28, speed=0.34, mastery=0.18, ki_control=0.05, pl=0.0017),
        extras={"multi_hit": 4, "combo_extender": True},
    ),
    _tech(
        "meteor_smash",
        "Meteor Smash",
        "melee",
        "A high-speed rush string ending in a heavy launcher or ground drive.",
        ["melee", "damage", "rush", "knockback"],
        20,
        8.0,
        effect=_damage(28, "impact", strength=0.34, speed=0.28, mastery=0.2, ki_control=0.06, pl=0.0019),
        extras={"multi_hit": 3, "knockback": "medium"},
    ),
    _tech(
        "dragon_fist",
        "Dragon Fist",
        "melee",
        "A legendary finishing strike that commits everything to one piercing rush impact.",
        ["melee", "damage", "finisher", "piercing"],
        40,
        14.0,
        effect=_damage(52, "pierce_impact", strength=0.38, speed=0.2, mastery=0.28, ki_control=0.12, pl=0.0027),
        extras={"guard_break": 0.2, "charge_synergy": 0.2},
        prerequisites={"quest": "dragon_fist_trial", "trainer": "goku"},
    ),
    _tech(
        "justice_rush",
        "Justice Rush",
        "melee",
        "A disciplined pride-rush sequence that rewards timing and stance control.",
        ["melee", "damage", "rush"],
        22,
        8.5,
        effect=_damage(27, "impact", strength=0.26, speed=0.32, mastery=0.24, ki_control=0.08, pl=0.0019),
        extras={"stance_bonus_hook": True},
    ),
    _tech(
        "mach_punch_barrage",
        "Mach Punch Barrage",
        "melee",
        "A blinding flurry of punches meant to overwhelm reactions and force mistakes.",
        ["melee", "damage", "combo", "rush"],
        18,
        6.5,
        effect=_damage(22, "impact", strength=0.22, speed=0.36, mastery=0.18, ki_control=0.05, pl=0.0016),
        extras={"multi_hit": 5, "stagger_bias": 0.08},
    ),
    _tech(
        "spirit_breaking_fist",
        "Spirit Breaking Fist",
        "melee",
        "A crushing anti-ki body blow intended to disrupt charges and reduce output windows.",
        ["melee", "damage", "control", "interrupt"],
        24,
        9.5,
        effect=_damage(30, "impact", strength=0.34, speed=0.2, mastery=0.22, ki_control=0.08, pl=0.0020),
        extras={"interrupts_charging": True, "ki_damage_hook": 12},
    ),
    _tech(
        "crusher_knee",
        "Crusher Knee",
        "melee",
        "A brutal close-range knee strike that spikes stagger and punishes bad guards.",
        ["melee", "damage", "knockback"],
        14,
        5.5,
        effect=_damage(20, "impact", strength=0.32, speed=0.22, mastery=0.16, ki_control=0.04, pl=0.0016),
        extras={"stagger_bias": 0.12, "guard_break": 0.08},
    ),
    _tech(
        "tail_sweep",
        "Tail Sweep",
        "melee",
        "A low sweeping strike used by tailed fighters and adaptable brawlers to unbalance foes.",
        ["melee", "damage", "control"],
        10,
        5.0,
        effect=_damage(16, "impact", strength=0.22, speed=0.24, mastery=0.14, ki_control=0.03, pl=0.0014),
        extras={"trip_hook": True},
        prerequisites={"race_any": ["saiyan", "half_breed", "biodroid"], "or_trainer": "vegeta"},
    ),
    _tech(
        "tri_beam",
        "Tri-Beam",
        "beam",
        "A life-draining compression blast that hits far above its size when committed.",
        ["ki", "beam", "damage", "advanced", "self_cost"],
        26,
        9.0,
        cast_time=0.35,
        effect=_damage(42, "beam", mastery=0.32, ki_control=0.34, strength=0.1, pl=0.0023),
        extras={"beam_struggle_participation": True, "self_hp_cost_hook": 8},
        prerequisites={"trainer": "tien"},
    ),
    # Technique-like transformation activators (stubs that call form system)
    _tech(
        "kaioken",
        "Kaioken",
        "transformation",
        "King Kai's explosive amplification technique that boosts output at mounting strain.",
        ["ki", "utility", "transformation"],
        18,
        3.0,
        effect={"type": "transform", "form_key": "kaioken", "summary": "Activate Kaioken form state"},
        target="self",
        range_band="self",
        prerequisites={"trainer": "king_kai", "quest": "snake_way_endurance"},
        extras={"delegates_to_form_system": True},
    ),
    _tech(
        "potential_unleashed_focus",
        "Potential Unleashed Focus",
        "transformation",
        "A steady ritual focus used to awaken latent power without rage instability.",
        ["ki", "utility", "transformation"],
        20,
        4.0,
        effect={"type": "transform", "form_key": "potential_unleashed", "summary": "Activate Potential Unleashed"},
        target="self",
        range_band="self",
        prerequisites={"trainer": "supreme_kai", "quest": "elder_kai_ritual"},
        extras={"delegates_to_form_system": True},
    ),
    _tech(
        "legendary_surge",
        "Legendary Surge",
        "transformation",
        "A dangerous trigger technique that hands control to the Legendary Super Saiyan progression state.",
        ["ki", "utility", "transformation", "legendary"],
        24,
        5.0,
        effect={"type": "transform", "form_key": "legendary_super_saiyan", "summary": "Engage LSSJ system"},
        target="self",
        range_band="self",
        prerequisites={"race_any": ["saiyan", "half_breed"], "lineage_flag": "legendary_seed"},
        extras={"delegates_to_lssj_system": True},
    ),
    _tech(
        "android_overclock",
        "Android Overclock",
        "transformation",
        "Route surplus reactor output into short-term combat acceleration at heat risk.",
        ["utility", "transformation", "android"],
        0,
        6.0,
        effect={"type": "transform", "form_key": "android_overclock", "summary": "Activate Android Overclock"},
        target="self",
        range_band="self",
        prerequisites={"race": "android", "quest": "capsule_lab_calibration"},
        extras={"delegates_to_form_system": True, "uses_heat_meter_hook": True},
    ),
    _tech(
        "regeneration_focus",
        "Regeneration Focus",
        "utility",
        "A meditative pulse that accelerates recovery by converting ki into stability.",
        ["ki", "utility", "self", "recovery"],
        20,
        12.0,
        effect={"type": "heal", "base_heal": 24, "summary": "Self-heal / recovery window"},
        target="self",
        range_band="self",
        prerequisites={"race_any": ["namekian", "majin", "biodroid"], "or_trainer": "piccolo"},
    ),
    _tech(
        "psychic_burst",
        "Psychic Burst",
        "control",
        "A Grey/Kai telekinetic shock that staggers targets and disrupts casts.",
        ["ki", "utility", "control", "interrupt"],
        23,
        8.0,
        effect={"type": "aoe_pulse", "base_damage": 14, "radius": 1, "summary": "Psychic stagger pulse"},
        target="area",
        range_band="short",
        prerequisites={"race_any": ["grey", "kai"], "or_trainer": "whis"},
        extras={"interrupt_bias": 0.18},
    ),
    # King Kai / Kaioken techniques
    _tech(
        "kaioken_charge",
        "Kaioken",
        "transformation",
        "Activate the Kaioken transformation. Hold to charge - x3 at 3s, x10 at 6s, x20 at 10s. Higher multipliers increase power but also strain and ki drain.",
        ["utility", "transformation", "kaioken", "strain", "hold_to_charge"],
        0,
        8.0,
        effect={"type": "transform", "form_key": "kaioken", "summary": "Activate Kaioken - hold to charge multipliers"},
        target="self",
        range_band="self",
        prerequisites={"trainer": "king_kai", "quest": "snake_way_endurance", "ki_control_min": 16},
        extras={"delegates_to_form_system": True, "hp_strain_hook": True, "hold_to_charge": True},
    ),
    _tech(
        "spirit_bomb_charge",
        "Spirit Bomb",
        "special",
        "Gather energy from all living things to create a devastating concentrated attack.",
        ["ki", "special", "charging", "nuke"],
        60,
        20.0,
        effect={"type": "charge_channel", "base_damage": 120, "summary": "Gather energy for massive nuke"},
        target="enemy",
        range_band="long",
        prerequisites={"trainer": "king_kai", "ki_control_min": 20},
        extras={"charge_bonus_multiplier": 0.25, "anti_stall_bias": 0.15},
    ),
    # Whis / Ultra Instinct techniques
    _tech(
        "ultra_instinct_sign",
        "Ultra Instinct Sign",
        "transformation",
        "Silver-haired Ultra Instinct state - instinctive movement without full mastery.",
        ["utility", "transformation", "ultra_instinct", "dodge"],
        0,
        10.0,
        effect={"type": "transform", "form_key": "ultra_instinct_sign", "summary": "Activate Ultra Instinct Sign (PL +48%, auto-dodge)"},
        target="self",
        range_band="self",
        prerequisites={"quest": "ultra_instinct_awakening", "mastery_min": 35, "ki_control_min": 32},
        extras={"delegates_to_form_system": True, "auto_dodge_hook": True, "counter_bonus": 0.18},
        aliases=["ui_sign", "uis"],
    ),
    _tech(
        "ultra_instinct",
        "Ultra Instinct",
        "transformation",
        "Mastered Ultra Instinct - complete autonomous combat with perfect efficiency.",
        ["utility", "transformation", "ultra_instinct", "mastered"],
        0,
        15.0,
        effect={"type": "transform", "form_key": "ultra_instinct", "summary": "Activate Mastered Ultra Instinct (PL +62%, perfect efficiency)"},
        target="self",
        range_band="self",
        prerequisites={"requires_form": "ultra_instinct_sign", "form_mastery_min": 45, "ki_control_min": 42, "quest": "ultra_instinct_mastery"},
        extras={"delegates_to_form_system": True, "auto_dodge_hook": True, "perfect_efficiency": True, "counter_bonus": 0.25},
        aliases=["ui", "mastered_ui"],
    ),
    _tech(
        "ultra_instinct_breached",
        "Ultra Instinct Breached",
        "transformation",
        "Overwhelmed Ultra Instinct - power beyond control with erratic output.",
        ["utility", "transformation", "ultra_instinct", "unstable"],
        0,
        12.0,
        effect={"type": "transform", "form_key": "ultra_instinct_breached", "summary": "Activate Breached UI (PL +55%, unstable power)"},
        target="self",
        range_band="self",
        prerequisites={"requires_form": "ultra_instinct_sign", "form_mastery_min": 25, "quest": "ui_overwhelm_event"},
        extras={"delegates_to_form_system": True, "auto_dodge_hook": True, "unstable_power": True, "control_penalty": 0.15},
        aliases=["breached_ui"],
    ),
    _tech(
        "angel_strike",
        "Angel Strike",
        "melee",
        "Whis's signature strike technique - impossibly fast movement with devastating follow-up.",
        ["melee", "strike", "combo", "angel"],
        18,
        4.0,
        effect={"type": "combo_strike", "base_damage": 22, "combo_hits": 3, "summary": "Fast 3-hit combo strike"},
        target="enemy",
        range_band="short",
        prerequisites={"trainer": "whis", "quest": "ultra_instinct_awakening"},
        extras={"combo_bias": 0.12, "dodge_bonus": 0.08},
    ),
    _tech(
        "ultra_instinct_dodge",
        "Ultra Instinct Dodge",
        "utility",
        "Instinctive dodge technique usable in any form - move before thinking.",
        ["utility", "dodge", "defensive", "ultra_instinct"],
        12,
        3.0,
        effect={"type": "evasion", "summary": "Instinctive dodge with counter window"},
        target="self",
        range_band="self",
        prerequisites={"trainer": "whis", "quest": "ultra_instinct_mastery"},
        extras={"evasion_bonus": 0.15, "counter_window": 1.5},
    ),
    # Items / Consumables
    _tech(
        "senzu_bean",
        "Senzu Bean",
        "item",
        "A mystical bean that fully restores health and ki, and heals all limb damage.",
        ["item", "consumable", "healing"],
        0,
        30.0,
        effect={"type": "full_heal", "summary": "Full HP/KI + limb heal"},
        target="self",
        range_band="self",
        prerequisites={"quest": "senzu_quest"},
    ),
    _tech(
        "dragon_ball",
        "Dragon Ball",
        "collectible",
        "A mystical orb with 4-stars. Collect all 7 to summon Shenron!",
        ["collectible", "dragon_ball", "rare"],
        0,
        0,
        effect={"type": "collectible", "summary": "1/7 Dragon Balls - find all to summon Shenron"},
        target="self",
        range_band="self",
    ),
    _tech(
        "summon_shenron",
        "Summon Shenron",
        "ultimate",
        "Summon the Eternal Dragon Shenron! Requires all 7 Dragon Balls.",
        ["ultimate", "summon", "dragon"],
        0,
        10.0,
        effect={"type": "summon_shenron", "summary": "Summon dragon for wish"},
        target="self",
        range_band="self",
        prerequisites={"requires_all_dragon_balls": True},
    ),
    _tech(
        "spirit_bomb",
        "Spirit Bomb",
        "ultimate",
        "Gather energy from all living things into a devastating attack. Requires charging but deals massive damage.",
        ["ultimate", "charging", "aoe", "energy"],
        0,  # No ki cost to cast (gathers from environment)
        15.0,  # Long charge time
        effect={"type": "spirit_bomb", "summary": "Massive damage that scales with PL gap"},
        target="enemy",
        range_band="far",
        prerequisites={"quest": "spirit_bomb_trial", "forms": ["super_saiyan"]},
        extras={"charge_multiplier": 3.0, "aoe_radius": 5},
    ),
    _tech(
        "healing_chamber",
        "Healing Chamber",
        "location",
        "Use a nearby healing chamber to slowly regenerate health and repair limbs.",
        ["location", "healing", "rest"],
        0,
        60.0,
        effect={"type": "location_heal", "summary": "Slow HP + limb repair at location"},
        target="self",
        range_band="self",
    ),
    # Equipment
    _tech(
        "weighted_clothing",
        "Weighted Clothing",
        "equipment",
        "Special training clothes that increase gravity resistance. Permanently boosts base stats.",
        ["equipment", "passive", "training"],
        0,
        0,
        effect={"type": "passive_boost", "summary": "+10% training efficiency"},
        target="self",
        range_band="self",
        prerequisites={"zeni_cost": 500},
    ),
    _tech(
        "scouter",
        "Scouter",
        "equipment",
        "A device that displays enemy power levels. Allows you to see PL gaps more clearly.",
        ["equipment", "scanner", "utility"],
        0,
        0,
        effect={"type": "pl_scanner", "summary": "Shows exact PL in combat"},
        target="self",
        range_band="self",
        prerequisites={"zeni_cost": 1000},
    ),
    # =================== FUSION TECHNIQUES ===================
    _tech(
        "metamoran_dance",
        "Metamoran Dance",
        "special",
        "The legendary dance technique used to fuse two warriors into one. Must be performed with a partner.",
        ["fusion", "special", "dance"],
        0,
        0,
        effect={"type": "fusion_dance", "summary": "Fuse with partner for 30 minutes"},
        target="partner",
        range_band="melee",
    ),
    _tech(
        "potara_earrings",
        "Potara Earrings",
        "equipment",
        "Sacred Potara earrings that enable fusion when worn by two warriors. Required for Potara fusion.",
        ["fusion", "equipment", "potara"],
        0,
        0,
        effect={"type": "fusion_item", "summary": "Required for Potara fusion"},
        target="self",
        range_band="self",
    ),
    _tech(
        "fusion_kamehameha",
        "Fusion Kamehameha",
        "beam",
        "A devastating beam attack that only fused warriors can use. Combines the energy of both fighters into one massive attack.",
        ["beam", "fusion", "ultimate"],
        35,
        45.0,
        damage_base=180,
        damage_factor=2.2,
        accuracy=95,
        vfx_id="vfx_fusion_beam_gold",
        effect={"type": "damage", "stun": 3, "beam_struggle_bonus": 0.25},
        target="enemy",
        range_band="far",
        prerequisites={"requires_fusion": True},
    ),
    _tech(
        "soul_buster",
        "Soul Buster",
        "blast",
        "The ultimate Potara fusion finishing technique. A massive energy sphere that obliterates everything in its path.",
        ["blast", "fusion", "ultimate"],
        40,
        55.0,
        damage_base=220,
        damage_factor=2.5,
        accuracy=92,
        vfx_id="vfx_soul_buster",
        effect={"type": "damage", "stun": 4, "armor_break": 1},
        target="enemy",
        range_band="far",
        prerequisites={"requires_fusion": True, "requires_form": "potara_fusion"},
    ),
    _tech(
        "stardust_fall",
        "Stardust Fall",
        "blast",
        "A barrage of explosive energy bullets unique to Metamoran fusions. Each shot packs incredible force.",
        ["blast", "fusion", "barrage"],
        25,
        30.0,
        damage_base=120,
        damage_factor=1.8,
        accuracy=90,
        vfx_id="vfx_stardust",
        effect={"type": "damage", "stun": 2},
        target="enemy",
        range_band="far",
        prerequisites={"requires_fusion": True, "requires_form": "metamoran_fusion"},
    ),
    _tech(
        "double_galick_cannon",
        "Double Galick Cannon",
        "beam",
        "A powerful beam attack that channels both fighters' energy simultaneously. Devastating against single targets.",
        ["beam", "fusion", "power"],
        30,
        38.0,
        damage_base=150,
        damage_factor=2.0,
        accuracy=93,
        vfx_id="vfx_galick_fusion",
        effect={"type": "damage", "stun": 3, "beam_struggle_bonus": 0.20},
        target="enemy",
        range_band="far",
        prerequisites={"requires_fusion": True},
    ),
]


TECHNIQUES = build_registry(_T)

# Transformation activation and core resource toggles are handled as first-class systems/commands.
# Keep the content definitions above for easy restoration, but prune them from the technique registry
# so the ability catalog remains exactly 50 entries as requested.
for _pruned in (
    "kaioken",
    "potential_unleashed_focus",
    "legendary_surge",
    "android_overclock",
    "ki_suppression",
    "power_up_charge",
):
    TECHNIQUES.pop(_pruned, None)


STARTER_TECHNIQUES = [
    "ki_blast",
    "kame_wave",
    "solar_flare",
    "guard",
    "afterimage_dash",
    "vanish_strike",
]


def get_technique(key_or_name):
    return find_by_key_or_name(TECHNIQUES, key_or_name)


def is_beam(tech_key):
    return "beam" in TECHNIQUES.get(tech_key, {}).get("tags", [])


def get_technique_categories():
    ordered = ["melee", "ki", "beam", "control", "utility", "defense", "movement", "transformation"]
    return ordered


def iter_techniques():
    for key in sorted(TECHNIQUES.keys()):
        yield key, TECHNIQUES[key]


def execute_technique_stub(caller, technique_key, target=None, context=None):
    """
    Placeholder executor used by commands and tests before combat resolution is finalized.
    """
    if technique_key not in TECHNIQUES:
        raise KeyError(f"Unknown technique: {technique_key}")
    technique = TECHNIQUES[technique_key]
    return make_stub_result(
        "technique",
        technique_key,
        caller=caller,
        target=target,
        payload={
            "effect": technique.get("effect", {}),
            "scaling": technique.get("scaling", {}),
            "context": context or {},
        },
    )


def validate_technique_registry():
    required_fields = {
        "id",
        "name",
        "description",
        "tags",
        "resource_costs",
        "cooldown",
        "effect",
        "target_rules",
        "prerequisites",
    }
    errors = []
    for key, data in TECHNIQUES.items():
        missing = sorted(required_fields - set(data.keys()))
        if missing:
            errors.append(f"{key}: missing {', '.join(missing)}")
        if "ki" not in data.get("resource_costs", {}):
            errors.append(f"{key}: resource_costs.ki missing")
    return errors
